# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
UserLevel.create!(level: "Super")
UserLevel.create!(level: "Admin")
UserLevel.create!(level: "Normal")

User.create!(name: "User 1", email: "example1@railstutorial.org", password: "foobar", password_confirmation: "foobar", is_user: true,
							user_level_id: 1)
User.create!(name: "User 2", email: "example2@railstutorial.org", password: "foobar", password_confirmation: "foobar", is_user: true,
							user_level_id: 2)
User.create!(name: "User 3", email: "example3@railstutorial.org", password: "foobar", password_confirmation: "foobar", is_user: true,
							user_level_id: 3)

ActorGender.create!(gender: "Male")
ActorGender.create!(gender: "Female")
ActorGender.create!(gender: "Other")

ActorCountry.create!(name: "USA")
ActorCountry.create!(name: "UK")
ActorCountry.create!(name: "India")
ActorCountry.create!(name: "Austrailia")
ActorCountry.create!(name: "Lebonan")
ActorCountry.create!(name: "Mexico")

ContentRating.create!(name: "G")
ContentRating.create!(name: "PG")
ContentRating.create!(name: "M")
ContentRating.create!(name: "R")
ContentRating.create!(name: "R+")

Genre.create!(name: "Action")
Genre.create!(name: "Comedy")
Genre.create!(name: "Marvel")
Genre.create!(name: "Horror")
Genre.create!(name: "Love")
Genre.create!(name: "Story")
Genre.create!(name: "Crime")
Genre.create!(name: "Adventure")
Genre.create!(name: "Thriller")
Genre.create!(name: "Mystery")
Genre.create!(name: "Si-Fi")
Genre.create!(name: "Drama")
Genre.create!(name: "Fantasy")

Actor.create!(name: "Jonny Depp", age: 50, actor_gender_id: 1, actor_country_id: 1)
Actor.create!(name: "Scarlet Johanson", age: 35, actor_gender_id: 2, actor_country_id: 1)
Actor.create!(name: "Chris Evens", age: 35, actor_gender_id: 1, actor_country_id: 1)
Actor.create!(name: "Brad Pitt", age: 48, actor_gender_id: 1, actor_country_id: 1)
Actor.create!(name: "Robert Downey Junior", age: 46, actor_gender_id: 1, actor_country_id: 1)
Actor.create!(name: "Leonado Dicaprio", age: 46, actor_gender_id: 1, actor_country_id: 1)
Actor.create!(name: "Chris Hemsworth", age: 35, actor_gender_id: 1, actor_country_id: 4)
Actor.create!(name: "Keanu Reeves", age: 57, actor_gender_id: 1, actor_country_id: 5)
Actor.create!(name: "Ian McShane", age: 78, actor_gender_id: 1, actor_country_id: 2)
Actor.create!(name: "Laurence Fishburne", age: 59, actor_gender_id: 1, actor_country_id: 1)
Actor.create!(name: "Asia Kate Dillon", age: 36, actor_gender_id: 2, actor_country_id: 1)
Actor.create!(name: "Halle Berry", age: 54, actor_gender_id: 2, actor_country_id: 1)
Actor.create!(name: "Chadwick Boseman", age: 45, actor_gender_id: 1, actor_country_id: 1)
Actor.create!(name: "Michael B. Jordan", age: 34, actor_gender_id: 1, actor_country_id: 1)
Actor.create!(name: "Lupita Nyong'o", age: 38, actor_gender_id: 2, actor_country_id: 6)
Actor.create!(name: "Danai Gurira", age: 43, actor_gender_id: 2, actor_country_id: 1)
Actor.create!(name: "Martin Freeman", age: 49, actor_gender_id: 1, actor_country_id: 2)
Actor.create!(name: "Margot Robbie", age: 30, actor_gender_id: 2, actor_country_id: 4)
Actor.create!(name: "Keira Knightley", age: 35, actor_gender_id: 2, actor_country_id: 2)
Actor.create!(name: "Orlando Bloom", age: 44, actor_gender_id: 1, actor_country_id: 2)
Actor.create!(name: "Chris Pratt", age: 41, actor_gender_id: 1, actor_country_id: 1)
Actor.create!(name: "Zoe Saldana", age: 42, actor_gender_id: 2, actor_country_id: 1)
Actor.create!(name: "Dave Bautista", age: 52, actor_gender_id: 1, actor_country_id: 1)

Video.create!(title: "Avengers - End Game", description: "Lorem ipsum, or lipsum as it is sometimes known...", release_date: Date.parse('2020-11-03'),thumbnail: File.read('app/assets/images/1.jpg'), content_rating: 1, actor_ids: [3, 7, 5, 2, 13, 21, 16, 23, 15], genre_ids: [1, 2, 3, 10, 11, 13])
Video.create!(title: "John Wick 3", description: "Lorem ipsum, or lipsum as it is sometimes known...", release_date: Date.parse('2019-05-09'),thumbnail: File.read('app/assets/images/3.jpeg'), content_rating: 4, actor_ids: [11, 12, 9, 8, 10], genre_ids: [1, 7, 8, 9, 10])
Video.create!(title: "Black Panther 1", description: "Lorem ipsum, or lipsum as it is sometimes known...", release_date: Date.parse('2018-01-29'),thumbnail: File.read('app/assets/images/4.jpg'), content_rating: 2, actor_ids: [13, 16, 15, 17, 14], genre_ids: [1, 3, 10, 11])
Video.create!(title: "Once apone a time in Hollywood", description: "Lorem ipsum, or lipsum as it is sometimes known...", release_date: Date.parse('2019-07-24'),thumbnail: File.read('app/assets/images/7.jpg'), content_rating: 4, actor_ids: [4, 6, 18], genre_ids: [2, 12])
Video.create!(title: "Pirates of the Caribean", description: "Lorem ipsum, or lipsum as it is sometimes known...", release_date: Date.parse('2003-06-28'),thumbnail: File.read('app/assets/images/8.jpg'), content_rating: 2, actor_ids: [1, 19, 20], genre_ids: [1, 8, 2, 13, 9])
Video.create!(title: "Avengers - Infinity War", description: "Lorem ipsum, or lipsum as it is sometimes known...", release_date: Date.parse('2018-04-23'),thumbnail: File.read('app/assets/images/10.jpg'), content_rating: 2, actor_ids: [13, 3, 7, 5, 2], genre_ids: [1, 3, 10, 11])
Video.create!(title: "Guardians of the galaxy 2", description: "Lorem ipsum, or lipsum as it is sometimes known...", release_date: Date.parse('2014-08-15'),thumbnail: File.read('app/assets/images/2.jpg'), content_rating: 1, actor_ids: [21, 23, 22], genre_ids: [1, 8, 2, 13, 3, 11])

Customer.create!(name: "Customer 1", email: "customer1@railstutorial.org", password: "foobar", is_user: false)
Customer.create!(name: "Customer 2", email: "customer2@railstutorial.org", password: "foobar", is_user: false)
Customer.create!(name: "Customer 3", email: "customer3@railstutorial.org", password: "foobar", is_user: false)

MediaType.create!(name: "Blueray")
MediaType.create!(name: "VHS")
MediaType.create!(name: "DVD")

Inventory.create!(price:10.0 , total_copies: 5, barcode_no: "asdf1234", video_id: 1, media_type_id: 1)
Inventory.create!(price: 5.0, total_copies: 3, barcode_no: "zxcv1234", video_id: 1, media_type_id: 2)
Inventory.create!(price: 8.0, total_copies: 2, barcode_no: "qwer1234", video_id: 2, media_type_id: 1)

MovieStock.create!(is_rented: false, inventory_id: 1)
MovieStock.create!(is_rented: false, inventory_id: 1)
MovieStock.create!(is_rented: false, inventory_id: 1)
MovieStock.create!(is_rented: false, inventory_id: 1)
MovieStock.create!(is_rented: false, inventory_id: 1)
MovieStock.create!(is_rented: false, inventory_id: 2)
MovieStock.create!(is_rented: false, inventory_id: 2)
MovieStock.create!(is_rented: false, inventory_id: 2)
MovieStock.create!(is_rented: false, inventory_id: 3)
MovieStock.create!(is_rented: false, inventory_id: 3)

CustomersMovieStocksUser.create!(price: 10.0, late_fee: 2.0, discount: 0.0, rented_date: Date.parse('2021-03-01'), returned_date: Date.parse('2021-03-10'), customer_id: 1, movie_stock_id: 1, user_id: 1)
CustomersMovieStocksUser.create!(price: 5.0, late_fee: , discount: , rented_date: Date.parse('2021-03-01'), returned_date: , customer_id: 1, movie_stock_id: 6, user_id: 1)
CustomersMovieStocksUser.create!(price: 8.0, late_fee: , discount: , rented_date: Date.parse('2021-03-01'), returned_date: , customer_id: 2, movie_stock_id: 9, user_id: 1)

Review.create!(rating: 5, comment: "nice..", customer_id: 1, video_id: 1)
Review.create!(rating: 3, comment: "ok..", customer_id: 2, video_id: 5)
Review.create!(rating: 1, comment: "bad..", customer_id: 3, video_id: 7)
